// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The AuthorisationChallengeRequest. </summary>
    public partial class AuthorisationChallengeRequest
    {
        /// <summary> Initializes a new instance of AuthorisationChallengeRequest. </summary>
        /// <param name="contextIdentifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="contextIdentifier"/> is null. </exception>
        public AuthorisationChallengeRequest(SubjectIdentifierByType contextIdentifier)
        {
            if (contextIdentifier == null)
            {
                throw new ArgumentNullException(nameof(contextIdentifier));
            }

            ContextIdentifier = contextIdentifier;
        }

        /// <summary> Gets the context identifier. </summary>
        public SubjectIdentifierByType ContextIdentifier { get; }
    }
}
