// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The AuthorisationChallengeResponse. </summary>
    public partial class AuthorisationChallengeResponse
    {
        /// <summary> Initializes a new instance of AuthorisationChallengeResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="challenge"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="challenge"/> is null. </exception>
        internal AuthorisationChallengeResponse(DateTimeOffset timestamp, string challenge)
        {
            if (challenge == null)
            {
                throw new ArgumentNullException(nameof(challenge));
            }

            Timestamp = timestamp;
            Challenge = challenge;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the challenge. </summary>
        public string Challenge { get; }
    }
}
