// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class AuthorisationChallengeResponse
    {
        internal static AuthorisationChallengeResponse DeserializeAuthorisationChallengeResponse(JsonElement element)
        {
            DateTimeOffset timestamp = default;
            string challenge = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("timestamp"))
                {
                    timestamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("challenge"))
                {
                    challenge = property.Value.GetString();
                    continue;
                }
            }
            return new AuthorisationChallengeResponse(timestamp, challenge);
        }
    }
}
