// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsParentType. </summary>
    public partial class CredentialsParentType : CredentialsBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsParentType. </summary>
        internal CredentialsParentType()
        {
            Type = "single_parent";
        }

        /// <summary> Initializes a new instance of CredentialsParentType. </summary>
        /// <param name="identifier"> Any object. </param>
        /// <param name="type"></param>
        /// <param name="credentialsRole"></param>
        internal CredentialsParentType(object identifier, string type, CredentialsRoleResponseStandardPlainType credentialsRole) : base(identifier, type)
        {
            CredentialsRole = credentialsRole;
            Type = type ?? "single_parent";
        }

        /// <summary> Gets the credentials role. </summary>
        public CredentialsRoleResponseStandardPlainType CredentialsRole { get; }
    }
}
