// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsIdentifierResponseInstitutionalNipType
    {
        internal static CredentialsIdentifierResponseInstitutionalNipType DeserializeCredentialsIdentifierResponseInstitutionalNipType(JsonElement element)
        {
            string identifier = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("identifier"))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsIdentifierResponseInstitutionalNipType(identifier);
        }
    }
}
