// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseGrantedForInstitutionType. </summary>
    public partial class CredentialsRoleResponseGrantedForInstitutionType : CredentialsRoleResponseBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsRoleResponseGrantedForInstitutionType. </summary>
        internal CredentialsRoleResponseGrantedForInstitutionType()
        {
            Type = "granted";
        }

        /// <summary> Initializes a new instance of CredentialsRoleResponseGrantedForInstitutionType. </summary>
        /// <param name="roleType"> Any object. </param>
        /// <param name="roleDescription"></param>
        /// <param name="type"></param>
        /// <param name="roleGrantorIdentifier"></param>
        internal CredentialsRoleResponseGrantedForInstitutionType(object roleType, string roleDescription, string type, CredentialsIdentifierResponseInstitutionalNipType roleGrantorIdentifier) : base(roleType, roleDescription, type)
        {
            RoleGrantorIdentifier = roleGrantorIdentifier;
            Type = type ?? "granted";
        }

        /// <summary> Gets the role grantor identifier. </summary>
        public CredentialsIdentifierResponseInstitutionalNipType RoleGrantorIdentifier { get; }
    }
}
