// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsPlainType. </summary>
    public partial class CredentialsPlainType
    {
        /// <summary> Initializes a new instance of CredentialsPlainType. </summary>
        internal CredentialsPlainType()
        {
            CredentialsRoleList = new ChangeTrackingList<CredentialsRoleResponseStandardDetailsType>();
        }

        /// <summary> Initializes a new instance of CredentialsPlainType. </summary>
        /// <param name="identifier"></param>
        /// <param name="credentialsRoleList"></param>
        internal CredentialsPlainType(CredentialsIdentifierResponseType identifier, IReadOnlyList<CredentialsRoleResponseStandardDetailsType> credentialsRoleList)
        {
            Identifier = identifier;
            CredentialsRoleList = credentialsRoleList;
        }

        /// <summary> Gets the identifier. </summary>
        public CredentialsIdentifierResponseType Identifier { get; }
        /// <summary> Gets the credentials role list. </summary>
        public IReadOnlyList<CredentialsRoleResponseStandardDetailsType> CredentialsRoleList { get; }
    }
}
