// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsPlainType
    {
        internal static CredentialsPlainType DeserializeCredentialsPlainType(JsonElement element)
        {
            Optional<CredentialsIdentifierResponseType> identifier = default;
            Optional<IReadOnlyList<CredentialsRoleResponseStandardDetailsType>> credentialsRoleList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("identifier"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    identifier = CredentialsIdentifierResponseType.DeserializeCredentialsIdentifierResponseType(property.Value);
                    continue;
                }
                if (property.NameEquals("credentialsRoleList"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<CredentialsRoleResponseStandardDetailsType> array = new List<CredentialsRoleResponseStandardDetailsType>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(CredentialsRoleResponseStandardDetailsType.DeserializeCredentialsRoleResponseStandardDetailsType(item));
                    }
                    credentialsRoleList = array;
                    continue;
                }
            }
            return new CredentialsPlainType(identifier.Value, Optional.ToList(credentialsRoleList));
        }
    }
}
