// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseTokenType. </summary>
    public partial class CredentialsRoleResponseTokenType : CredentialsRoleResponseBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsRoleResponseTokenType. </summary>
        internal CredentialsRoleResponseTokenType()
        {
            Type = "token";
        }

        /// <summary> Initializes a new instance of CredentialsRoleResponseTokenType. </summary>
        /// <param name="roleType"> Any object. </param>
        /// <param name="roleDescription"></param>
        /// <param name="type"></param>
        internal CredentialsRoleResponseTokenType(object roleType, string roleDescription, string type) : base(roleType, roleDescription, type)
        {
            Type = type ?? "token";
        }
    }
}
