// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierRequestIndividualNipType. </summary>
    public partial class CredentialsIdentifierRequestIndividualNipType : CredentialsIdentifierRequestType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierRequestIndividualNipType. </summary>
        public CredentialsIdentifierRequestIndividualNipType()
        {
            Type = "nip";
        }
    }
}
