// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierRequestIndividualPeselType. </summary>
    public partial class CredentialsIdentifierRequestIndividualPeselType : CredentialsIdentifierRequestType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierRequestIndividualPeselType. </summary>
        public CredentialsIdentifierRequestIndividualPeselType()
        {
            Type = "pesel";
        }
    }
}
