// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseGrantedForInstitutionTypeRoleType. </summary>
    public readonly partial struct CredentialsRoleResponseGrantedForInstitutionTypeRoleType : IEquatable<CredentialsRoleResponseGrantedForInstitutionTypeRoleType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleResponseGrantedForInstitutionTypeRoleType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleResponseGrantedForInstitutionTypeRoleType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string InvoiceReadValue = "invoice_read";
        private const string InvoiceWriteValue = "invoice_write";
        private const string PaymentConfirmationWriteValue = "payment_confirmation_write";
        private const string SelfInvoicingValue = "self_invoicing";
        private const string TaxRepresentativeValue = "tax_representative";
        private const string CourtBailiffValue = "court_bailiff";
        private const string EnforcementAuthorityValue = "enforcement_authority";

        /// <summary> invoice_read. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType InvoiceRead { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(InvoiceReadValue);
        /// <summary> invoice_write. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType InvoiceWrite { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(InvoiceWriteValue);
        /// <summary> payment_confirmation_write. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType PaymentConfirmationWrite { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(PaymentConfirmationWriteValue);
        /// <summary> self_invoicing. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType SelfInvoicing { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(SelfInvoicingValue);
        /// <summary> tax_representative. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType TaxRepresentative { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(TaxRepresentativeValue);
        /// <summary> court_bailiff. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType CourtBailiff { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(CourtBailiffValue);
        /// <summary> enforcement_authority. </summary>
        public static CredentialsRoleResponseGrantedForInstitutionTypeRoleType EnforcementAuthority { get; } = new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(EnforcementAuthorityValue);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseGrantedForInstitutionTypeRoleType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleResponseGrantedForInstitutionTypeRoleType left, CredentialsRoleResponseGrantedForInstitutionTypeRoleType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseGrantedForInstitutionTypeRoleType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleResponseGrantedForInstitutionTypeRoleType left, CredentialsRoleResponseGrantedForInstitutionTypeRoleType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleResponseGrantedForInstitutionTypeRoleType"/>. </summary>
        public static implicit operator CredentialsRoleResponseGrantedForInstitutionTypeRoleType(string value) => new CredentialsRoleResponseGrantedForInstitutionTypeRoleType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleResponseGrantedForInstitutionTypeRoleType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleResponseGrantedForInstitutionTypeRoleType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
