// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseStandardDetailsType. </summary>
    public partial class CredentialsRoleResponseStandardDetailsType : CredentialsRoleResponseBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsRoleResponseStandardDetailsType. </summary>
        internal CredentialsRoleResponseStandardDetailsType()
        {
            Type = "standard_details";
        }

        /// <summary> Initializes a new instance of CredentialsRoleResponseStandardDetailsType. </summary>
        /// <param name="roleType"> Any object. </param>
        /// <param name="roleDescription"></param>
        /// <param name="type"></param>
        /// <param name="credentialsAssignmentType"></param>
        /// <param name="roleAssigningAuthorIdentifier"></param>
        internal CredentialsRoleResponseStandardDetailsType(object roleType, string roleDescription, string type, CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType? credentialsAssignmentType, CredentialsIdentifierResponseType roleAssigningAuthorIdentifier) : base(roleType, roleDescription, type)
        {
            CredentialsAssignmentType = credentialsAssignmentType;
            RoleAssigningAuthorIdentifier = roleAssigningAuthorIdentifier;
            Type = type ?? "standard_details";
        }

        /// <summary> Gets the credentials assignment type. </summary>
        public CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType? CredentialsAssignmentType { get; }
        /// <summary> Gets the role assigning author identifier. </summary>
        public CredentialsIdentifierResponseType RoleAssigningAuthorIdentifier { get; }
    }
}
