// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseIndividualCertificateFingerprintType. </summary>
    public partial class CredentialsIdentifierResponseIndividualCertificateFingerprintType : CredentialsIdentifierResponseType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualCertificateFingerprintType. </summary>
        internal CredentialsIdentifierResponseIndividualCertificateFingerprintType()
        {
            Type = "fingerprint";
        }

        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualCertificateFingerprintType. </summary>
        /// <param name="identifier"></param>
        /// <param name="type"></param>
        internal CredentialsIdentifierResponseIndividualCertificateFingerprintType(string identifier, string type) : base(identifier, type)
        {
            Type = type ?? "fingerprint";
        }
    }
}
