// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType. </summary>
    public readonly partial struct CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType : IEquatable<CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string SystemValue = "system";
        private const string UserValue = "user";

        /// <summary> system. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType System { get; } = new CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType(SystemValue);
        /// <summary> user. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType User { get; } = new CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType(UserValue);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType left, CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType left, CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType"/>. </summary>
        public static implicit operator CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType(string value) => new CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleResponseStandardDetailsTypeCredentialsAssignmentType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
