// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleRequestStandardBaseTypeRoleType. </summary>
    public readonly partial struct CredentialsRoleRequestStandardBaseTypeRoleType : IEquatable<CredentialsRoleRequestStandardBaseTypeRoleType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleRequestStandardBaseTypeRoleType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleRequestStandardBaseTypeRoleType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string IntrospectionValue = "introspection";
        private const string InvoiceReadValue = "invoice_read";
        private const string InvoiceWriteValue = "invoice_write";
        private const string PaymentConfirmationWriteValue = "payment_confirmation_write";
        private const string CredentialsReadValue = "credentials_read";
        private const string CredentialsManageValue = "credentials_manage";
        private const string SelfInvoicingValue = "self_invoicing";
        private const string TaxRepresentativeValue = "tax_representative";
        private const string EnforcementOperationsValue = "enforcement_operations";

        /// <summary> introspection. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType Introspection { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(IntrospectionValue);
        /// <summary> invoice_read. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType InvoiceRead { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(InvoiceReadValue);
        /// <summary> invoice_write. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType InvoiceWrite { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(InvoiceWriteValue);
        /// <summary> payment_confirmation_write. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType PaymentConfirmationWrite { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(PaymentConfirmationWriteValue);
        /// <summary> credentials_read. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType CredentialsRead { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(CredentialsReadValue);
        /// <summary> credentials_manage. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType CredentialsManage { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(CredentialsManageValue);
        /// <summary> self_invoicing. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType SelfInvoicing { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(SelfInvoicingValue);
        /// <summary> tax_representative. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType TaxRepresentative { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(TaxRepresentativeValue);
        /// <summary> enforcement_operations. </summary>
        public static CredentialsRoleRequestStandardBaseTypeRoleType EnforcementOperations { get; } = new CredentialsRoleRequestStandardBaseTypeRoleType(EnforcementOperationsValue);
        /// <summary> Determines if two <see cref="CredentialsRoleRequestStandardBaseTypeRoleType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleRequestStandardBaseTypeRoleType left, CredentialsRoleRequestStandardBaseTypeRoleType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleRequestStandardBaseTypeRoleType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleRequestStandardBaseTypeRoleType left, CredentialsRoleRequestStandardBaseTypeRoleType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleRequestStandardBaseTypeRoleType"/>. </summary>
        public static implicit operator CredentialsRoleRequestStandardBaseTypeRoleType(string value) => new CredentialsRoleRequestStandardBaseTypeRoleType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleRequestStandardBaseTypeRoleType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleRequestStandardBaseTypeRoleType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
