// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseType. </summary>
    public partial class CredentialsIdentifierResponseType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseType. </summary>
        internal CredentialsIdentifierResponseType()
        {
        }

        /// <summary> Initializes a new instance of CredentialsIdentifierResponseType. </summary>
        /// <param name="identifier"></param>
        /// <param name="type"></param>
        internal CredentialsIdentifierResponseType(string identifier, string type)
        {
            Identifier = identifier;
            Type = type;
        }

        /// <summary> Gets the identifier. </summary>
        public string Identifier { get; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
