// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsBaseTypeObject. </summary>
    public partial class CredentialsBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsBaseTypeObject. </summary>
        internal CredentialsBaseTypeObject()
        {
        }

        /// <summary> Initializes a new instance of CredentialsBaseTypeObject. </summary>
        /// <param name="identifier"> Any object. </param>
        /// <param name="type"></param>
        internal CredentialsBaseTypeObject(object identifier, string type)
        {
            Identifier = identifier;
            Type = type;
        }

        /// <summary> Any object. </summary>
        public object Identifier { get; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
