// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsRoleResponseBaseTypeObject
    {
        internal static CredentialsRoleResponseBaseTypeObject DeserializeCredentialsRoleResponseBaseTypeObject(JsonElement element)
        {
            if (element.TryGetProperty("type", out JsonElement discriminator))
            {
                switch (discriminator.GetString())
                {
                    case "granted": return CredentialsRoleResponseGrantedForInstitutionType.DeserializeCredentialsRoleResponseGrantedForInstitutionType(element);
                    case "standard_details": return CredentialsRoleResponseStandardDetailsType.DeserializeCredentialsRoleResponseStandardDetailsType(element);
                    case "token": return CredentialsRoleResponseTokenType.DeserializeCredentialsRoleResponseTokenType(element);
                    case "standard_plain": return CredentialsRoleResponseStandardPlainType.DeserializeCredentialsRoleResponseStandardPlainType(element);
                }
            }
            Optional<object> roleType = default;
            Optional<string> roleDescription = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("roleType"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    roleType = property.Value.GetObject();
                    continue;
                }
                if (property.NameEquals("roleDescription"))
                {
                    roleDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsRoleResponseBaseTypeObject(roleType.Value, roleDescription.Value, type);
        }
    }
}
