// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseBaseTypeObject. </summary>
    public partial class CredentialsRoleResponseBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsRoleResponseBaseTypeObject. </summary>
        internal CredentialsRoleResponseBaseTypeObject()
        {
        }

        /// <summary> Initializes a new instance of CredentialsRoleResponseBaseTypeObject. </summary>
        /// <param name="roleType"> Any object. </param>
        /// <param name="roleDescription"></param>
        /// <param name="type"></param>
        internal CredentialsRoleResponseBaseTypeObject(object roleType, string roleDescription, string type)
        {
            RoleType = roleType;
            RoleDescription = roleDescription;
            Type = type;
        }

        /// <summary> Any object. </summary>
        public object RoleType { get; }
        /// <summary> Gets the role description. </summary>
        public string RoleDescription { get; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
