// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsParentType
    {
        internal static CredentialsParentType DeserializeCredentialsParentType(JsonElement element)
        {
            Optional<CredentialsRoleResponseStandardPlainType> credentialsRole = default;
            Optional<object> identifier = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("credentialsRole"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    credentialsRole = CredentialsRoleResponseStandardPlainType.DeserializeCredentialsRoleResponseStandardPlainType(property.Value);
                    continue;
                }
                if (property.NameEquals("identifier"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    identifier = property.Value.GetObject();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsParentType(identifier.Value, type, credentialsRole.Value);
        }
    }
}
