// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseInstitutionalNipType. </summary>
    public partial class CredentialsIdentifierResponseInstitutionalNipType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseInstitutionalNipType. </summary>
        /// <param name="identifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/> is null. </exception>
        internal CredentialsIdentifierResponseInstitutionalNipType(string identifier)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }

            Identifier = identifier;
        }

        /// <summary> Gets the identifier. </summary>
        public string Identifier { get; }
    }
}
