// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierRequestInstitutionalNipType. </summary>
    public partial class CredentialsIdentifierRequestInstitutionalNipType : CredentialsIdentifierRequestType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierRequestInstitutionalNipType. </summary>
        public CredentialsIdentifierRequestInstitutionalNipType()
        {
            Type = "onip";
        }
    }
}
