// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsIdentifierResponseIndividualCertificateFingerprintType
    {
        internal static CredentialsIdentifierResponseIndividualCertificateFingerprintType DeserializeCredentialsIdentifierResponseIndividualCertificateFingerprintType(JsonElement element)
        {
            Optional<string> identifier = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("identifier"))
                {
                    identifier = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsIdentifierResponseIndividualCertificateFingerprintType(identifier.Value, type);
        }
    }
}
