// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsRoleResponseTokenType
    {
        internal static CredentialsRoleResponseTokenType DeserializeCredentialsRoleResponseTokenType(JsonElement element)
        {
            Optional<object> roleType = default;
            Optional<string> roleDescription = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("roleType"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    roleType = property.Value.GetObject();
                    continue;
                }
                if (property.NameEquals("roleDescription"))
                {
                    roleDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsRoleResponseTokenType(roleType.Value, roleDescription.Value, type);
        }
    }
}
