// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class CredentialsRoleResponseGrantedForInstitutionType
    {
        internal static CredentialsRoleResponseGrantedForInstitutionType DeserializeCredentialsRoleResponseGrantedForInstitutionType(JsonElement element)
        {
            Optional<CredentialsIdentifierResponseInstitutionalNipType> roleGrantorIdentifier = default;
            Optional<object> roleType = default;
            Optional<string> roleDescription = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("roleGrantorIdentifier"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    roleGrantorIdentifier = CredentialsIdentifierResponseInstitutionalNipType.DeserializeCredentialsIdentifierResponseInstitutionalNipType(property.Value);
                    continue;
                }
                if (property.NameEquals("roleType"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    roleType = property.Value.GetObject();
                    continue;
                }
                if (property.NameEquals("roleDescription"))
                {
                    roleDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new CredentialsRoleResponseGrantedForInstitutionType(roleType.Value, roleDescription.Value, type, roleGrantorIdentifier.Value);
        }
    }
}
