// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierRequestType. </summary>
    public partial class CredentialsIdentifierRequestType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierRequestType. </summary>
        public CredentialsIdentifierRequestType()
        {
        }

        /// <summary> Gets or sets the identifier. </summary>
        public string Identifier { get; set; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
