// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseStandardPlainType. </summary>
    public partial class CredentialsRoleResponseStandardPlainType : CredentialsRoleResponseBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsRoleResponseStandardPlainType. </summary>
        internal CredentialsRoleResponseStandardPlainType()
        {
            Type = "standard_plain";
        }

        /// <summary> Initializes a new instance of CredentialsRoleResponseStandardPlainType. </summary>
        /// <param name="roleType"> Any object. </param>
        /// <param name="roleDescription"></param>
        /// <param name="type"></param>
        internal CredentialsRoleResponseStandardPlainType(object roleType, string roleDescription, string type) : base(roleType, roleDescription, type)
        {
            Type = type ?? "standard_plain";
        }
    }
}
