// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsTokenType. </summary>
    public partial class CredentialsTokenType : CredentialsBaseTypeObject
    {
        /// <summary> Initializes a new instance of CredentialsTokenType. </summary>
        internal CredentialsTokenType()
        {
            CredentialsRoleList = new ChangeTrackingList<CredentialsRoleResponseTokenType>();
            Type = "list_token";
        }

        /// <summary> Initializes a new instance of CredentialsTokenType. </summary>
        /// <param name="identifier"> Any object. </param>
        /// <param name="type"></param>
        /// <param name="credentialsRoleList"></param>
        /// <param name="parent"></param>
        /// <param name="description"></param>
        /// <param name="status"></param>
        internal CredentialsTokenType(object identifier, string type, IReadOnlyList<CredentialsRoleResponseTokenType> credentialsRoleList, CredentialsPlainType parent, string description, int? status) : base(identifier, type)
        {
            CredentialsRoleList = credentialsRoleList;
            Parent = parent;
            Description = description;
            Status = status;
            Type = type ?? "list_token";
        }

        /// <summary> Gets the credentials role list. </summary>
        public IReadOnlyList<CredentialsRoleResponseTokenType> CredentialsRoleList { get; }
        /// <summary> Gets the parent. </summary>
        public CredentialsPlainType Parent { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> Gets the status. </summary>
        public int? Status { get; }
    }
}
