// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseStandardDetailsTypeRoleType. </summary>
    public readonly partial struct CredentialsRoleResponseStandardDetailsTypeRoleType : IEquatable<CredentialsRoleResponseStandardDetailsTypeRoleType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleResponseStandardDetailsTypeRoleType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleResponseStandardDetailsTypeRoleType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string OwnerValue = "owner";
        private const string IntrospectionValue = "introspection";
        private const string InvoiceReadValue = "invoice_read";
        private const string InvoiceWriteValue = "invoice_write";
        private const string PaymentConfirmationWriteValue = "payment_confirmation_write";
        private const string CredentialsReadValue = "credentials_read";
        private const string CredentialsManageValue = "credentials_manage";
        private const string SelfInvoicingValue = "self_invoicing";
        private const string TaxRepresentativeValue = "tax_representative";
        private const string EnforcementOperationsValue = "enforcement_operations";
        private const string CourtBailiffValue = "court_bailiff";
        private const string EnforcementAuthorityValue = "enforcement_authority";

        /// <summary> owner. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType Owner { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(OwnerValue);
        /// <summary> introspection. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType Introspection { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(IntrospectionValue);
        /// <summary> invoice_read. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType InvoiceRead { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(InvoiceReadValue);
        /// <summary> invoice_write. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType InvoiceWrite { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(InvoiceWriteValue);
        /// <summary> payment_confirmation_write. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType PaymentConfirmationWrite { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(PaymentConfirmationWriteValue);
        /// <summary> credentials_read. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType CredentialsRead { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(CredentialsReadValue);
        /// <summary> credentials_manage. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType CredentialsManage { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(CredentialsManageValue);
        /// <summary> self_invoicing. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType SelfInvoicing { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(SelfInvoicingValue);
        /// <summary> tax_representative. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType TaxRepresentative { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(TaxRepresentativeValue);
        /// <summary> enforcement_operations. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType EnforcementOperations { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(EnforcementOperationsValue);
        /// <summary> court_bailiff. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType CourtBailiff { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(CourtBailiffValue);
        /// <summary> enforcement_authority. </summary>
        public static CredentialsRoleResponseStandardDetailsTypeRoleType EnforcementAuthority { get; } = new CredentialsRoleResponseStandardDetailsTypeRoleType(EnforcementAuthorityValue);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardDetailsTypeRoleType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleResponseStandardDetailsTypeRoleType left, CredentialsRoleResponseStandardDetailsTypeRoleType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardDetailsTypeRoleType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleResponseStandardDetailsTypeRoleType left, CredentialsRoleResponseStandardDetailsTypeRoleType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleResponseStandardDetailsTypeRoleType"/>. </summary>
        public static implicit operator CredentialsRoleResponseStandardDetailsTypeRoleType(string value) => new CredentialsRoleResponseStandardDetailsTypeRoleType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleResponseStandardDetailsTypeRoleType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleResponseStandardDetailsTypeRoleType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
