// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleRequestStandardBaseType. </summary>
    public partial class CredentialsRoleRequestStandardBaseType
    {
        /// <summary> Initializes a new instance of CredentialsRoleRequestStandardBaseType. </summary>
        /// <param name="roleType"></param>
        public CredentialsRoleRequestStandardBaseType(CredentialsRoleRequestStandardBaseTypeRoleType roleType)
        {
            RoleType = roleType;
        }

        /// <summary> Gets the role type. </summary>
        public CredentialsRoleRequestStandardBaseTypeRoleType RoleType { get; }
    }
}
