// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseIndividualNipType. </summary>
    public partial class CredentialsIdentifierResponseIndividualNipType : CredentialsIdentifierResponseType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualNipType. </summary>
        internal CredentialsIdentifierResponseIndividualNipType()
        {
            Type = "nip";
        }

        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualNipType. </summary>
        /// <param name="identifier"></param>
        /// <param name="type"></param>
        internal CredentialsIdentifierResponseIndividualNipType(string identifier, string type) : base(identifier, type)
        {
            Type = type ?? "nip";
        }
    }
}
