// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseIndividualPeselType. </summary>
    public partial class CredentialsIdentifierResponseIndividualPeselType : CredentialsIdentifierResponseType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualPeselType. </summary>
        internal CredentialsIdentifierResponseIndividualPeselType()
        {
            Type = "pesel";
        }

        /// <summary> Initializes a new instance of CredentialsIdentifierResponseIndividualPeselType. </summary>
        /// <param name="identifier"></param>
        /// <param name="type"></param>
        internal CredentialsIdentifierResponseIndividualPeselType(string identifier, string type) : base(identifier, type)
        {
            Type = type ?? "pesel";
        }
    }
}
