// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierResponseSystemType. </summary>
    public partial class CredentialsIdentifierResponseSystemType : CredentialsIdentifierResponseType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierResponseSystemType. </summary>
        internal CredentialsIdentifierResponseSystemType()
        {
            Type = "system";
        }

        /// <summary> Initializes a new instance of CredentialsIdentifierResponseSystemType. </summary>
        /// <param name="identifier"></param>
        /// <param name="type"></param>
        internal CredentialsIdentifierResponseSystemType(string identifier, string type) : base(identifier, type)
        {
            Type = type ?? "system";
        }
    }
}
