// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsIdentifierRequestIndividualCertificateFingerprintType. </summary>
    public partial class CredentialsIdentifierRequestIndividualCertificateFingerprintType : CredentialsIdentifierRequestType
    {
        /// <summary> Initializes a new instance of CredentialsIdentifierRequestIndividualCertificateFingerprintType. </summary>
        public CredentialsIdentifierRequestIndividualCertificateFingerprintType()
        {
            Type = "fingerprint";
        }
    }
}
