// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseStandardPlainTypeRoleType. </summary>
    public readonly partial struct CredentialsRoleResponseStandardPlainTypeRoleType : IEquatable<CredentialsRoleResponseStandardPlainTypeRoleType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleResponseStandardPlainTypeRoleType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleResponseStandardPlainTypeRoleType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string OwnerValue = "owner";
        private const string IntrospectionValue = "introspection";
        private const string InvoiceReadValue = "invoice_read";
        private const string InvoiceWriteValue = "invoice_write";
        private const string PaymentConfirmationWriteValue = "payment_confirmation_write";
        private const string CredentialsReadValue = "credentials_read";
        private const string CredentialsManageValue = "credentials_manage";
        private const string SelfInvoicingValue = "self_invoicing";
        private const string TaxRepresentativeValue = "tax_representative";
        private const string EnforcementOperationsValue = "enforcement_operations";
        private const string CourtBailiffValue = "court_bailiff";
        private const string EnforcementAuthorityValue = "enforcement_authority";

        /// <summary> owner. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType Owner { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(OwnerValue);
        /// <summary> introspection. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType Introspection { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(IntrospectionValue);
        /// <summary> invoice_read. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType InvoiceRead { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(InvoiceReadValue);
        /// <summary> invoice_write. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType InvoiceWrite { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(InvoiceWriteValue);
        /// <summary> payment_confirmation_write. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType PaymentConfirmationWrite { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(PaymentConfirmationWriteValue);
        /// <summary> credentials_read. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType CredentialsRead { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(CredentialsReadValue);
        /// <summary> credentials_manage. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType CredentialsManage { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(CredentialsManageValue);
        /// <summary> self_invoicing. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType SelfInvoicing { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(SelfInvoicingValue);
        /// <summary> tax_representative. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType TaxRepresentative { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(TaxRepresentativeValue);
        /// <summary> enforcement_operations. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType EnforcementOperations { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(EnforcementOperationsValue);
        /// <summary> court_bailiff. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType CourtBailiff { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(CourtBailiffValue);
        /// <summary> enforcement_authority. </summary>
        public static CredentialsRoleResponseStandardPlainTypeRoleType EnforcementAuthority { get; } = new CredentialsRoleResponseStandardPlainTypeRoleType(EnforcementAuthorityValue);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardPlainTypeRoleType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleResponseStandardPlainTypeRoleType left, CredentialsRoleResponseStandardPlainTypeRoleType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseStandardPlainTypeRoleType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleResponseStandardPlainTypeRoleType left, CredentialsRoleResponseStandardPlainTypeRoleType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleResponseStandardPlainTypeRoleType"/>. </summary>
        public static implicit operator CredentialsRoleResponseStandardPlainTypeRoleType(string value) => new CredentialsRoleResponseStandardPlainTypeRoleType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleResponseStandardPlainTypeRoleType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleResponseStandardPlainTypeRoleType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
