// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The CredentialsRoleResponseTokenTypeRoleType. </summary>
    public readonly partial struct CredentialsRoleResponseTokenTypeRoleType : IEquatable<CredentialsRoleResponseTokenTypeRoleType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="CredentialsRoleResponseTokenTypeRoleType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public CredentialsRoleResponseTokenTypeRoleType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string IntrospectionValue = "introspection";
        private const string InvoiceReadValue = "invoice_read";
        private const string InvoiceWriteValue = "invoice_write";
        private const string PaymentConfirmationWriteValue = "payment_confirmation_write";
        private const string CredentialsReadValue = "credentials_read";
        private const string CredentialsManageValue = "credentials_manage";
        private const string EnforcementOperationsValue = "enforcement_operations";

        /// <summary> introspection. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType Introspection { get; } = new CredentialsRoleResponseTokenTypeRoleType(IntrospectionValue);
        /// <summary> invoice_read. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType InvoiceRead { get; } = new CredentialsRoleResponseTokenTypeRoleType(InvoiceReadValue);
        /// <summary> invoice_write. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType InvoiceWrite { get; } = new CredentialsRoleResponseTokenTypeRoleType(InvoiceWriteValue);
        /// <summary> payment_confirmation_write. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType PaymentConfirmationWrite { get; } = new CredentialsRoleResponseTokenTypeRoleType(PaymentConfirmationWriteValue);
        /// <summary> credentials_read. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType CredentialsRead { get; } = new CredentialsRoleResponseTokenTypeRoleType(CredentialsReadValue);
        /// <summary> credentials_manage. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType CredentialsManage { get; } = new CredentialsRoleResponseTokenTypeRoleType(CredentialsManageValue);
        /// <summary> enforcement_operations. </summary>
        public static CredentialsRoleResponseTokenTypeRoleType EnforcementOperations { get; } = new CredentialsRoleResponseTokenTypeRoleType(EnforcementOperationsValue);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseTokenTypeRoleType"/> values are the same. </summary>
        public static bool operator ==(CredentialsRoleResponseTokenTypeRoleType left, CredentialsRoleResponseTokenTypeRoleType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="CredentialsRoleResponseTokenTypeRoleType"/> values are not the same. </summary>
        public static bool operator !=(CredentialsRoleResponseTokenTypeRoleType left, CredentialsRoleResponseTokenTypeRoleType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="CredentialsRoleResponseTokenTypeRoleType"/>. </summary>
        public static implicit operator CredentialsRoleResponseTokenTypeRoleType(string value) => new CredentialsRoleResponseTokenTypeRoleType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is CredentialsRoleResponseTokenTypeRoleType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(CredentialsRoleResponseTokenTypeRoleType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
