// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The ExceptionType. </summary>
    public partial class ExceptionType
    {
        /// <summary> Initializes a new instance of ExceptionType. </summary>
        /// <param name="serviceCtx"></param>
        /// <param name="serviceCode"></param>
        /// <param name="serviceName"></param>
        /// <param name="timestamp"></param>
        /// <param name="exceptionDetailList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="serviceCtx"/>, <paramref name="serviceCode"/>, <paramref name="serviceName"/> or <paramref name="exceptionDetailList"/> is null. </exception>
        internal ExceptionType(string serviceCtx, string serviceCode, string serviceName, DateTimeOffset timestamp, IEnumerable<ExceptionDetailType> exceptionDetailList)
        {
            if (serviceCtx == null)
            {
                throw new ArgumentNullException(nameof(serviceCtx));
            }
            if (serviceCode == null)
            {
                throw new ArgumentNullException(nameof(serviceCode));
            }
            if (serviceName == null)
            {
                throw new ArgumentNullException(nameof(serviceName));
            }
            if (exceptionDetailList == null)
            {
                throw new ArgumentNullException(nameof(exceptionDetailList));
            }

            ServiceCtx = serviceCtx;
            ServiceCode = serviceCode;
            ServiceName = serviceName;
            Timestamp = timestamp;
            ExceptionDetailList = exceptionDetailList.ToList();
        }

        /// <summary> Initializes a new instance of ExceptionType. </summary>
        /// <param name="serviceCtx"></param>
        /// <param name="serviceCode"></param>
        /// <param name="serviceName"></param>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="exceptionDetailList"></param>
        internal ExceptionType(string serviceCtx, string serviceCode, string serviceName, DateTimeOffset timestamp, string referenceNumber, IReadOnlyList<ExceptionDetailType> exceptionDetailList)
        {
            ServiceCtx = serviceCtx;
            ServiceCode = serviceCode;
            ServiceName = serviceName;
            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            ExceptionDetailList = exceptionDetailList;
        }

        /// <summary> Gets the service ctx. </summary>
        public string ServiceCtx { get; }
        /// <summary> Gets the service code. </summary>
        public string ServiceCode { get; }
        /// <summary> Gets the service name. </summary>
        public string ServiceName { get; }
        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the exception detail list. </summary>
        public IReadOnlyList<ExceptionDetailType> ExceptionDetailList { get; }
    }
}
