// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The ExceptionResponse. </summary>
    public partial class ExceptionResponse
    {
        /// <summary> Initializes a new instance of ExceptionResponse. </summary>
        /// <param name="exception"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="exception"/> is null. </exception>
        internal ExceptionResponse(ExceptionType exception)
        {
            if (exception == null)
            {
                throw new ArgumentNullException(nameof(exception));
            }

            Exception = exception;
        }

        /// <summary> Gets the exception. </summary>
        public ExceptionType Exception { get; }
    }
}
