// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class FileUnlimitedHashType
    {
        internal static FileUnlimitedHashType DeserializeFileUnlimitedHashType(JsonElement element)
        {
            HashSHAType hashSHA = default;
            int fileSize = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("hashSHA"))
                {
                    hashSHA = HashSHAType.DeserializeHashSHAType(property.Value);
                    continue;
                }
                if (property.NameEquals("fileSize"))
                {
                    fileSize = property.Value.GetInt32();
                    continue;
                }
            }
            return new FileUnlimitedHashType(hashSHA, fileSize);
        }
    }
}
