// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The FinishRequest. </summary>
    public partial class FinishRequest
    {
        /// <summary> Initializes a new instance of FinishRequest. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> is null. </exception>
        public FinishRequest(DateTimeOffset timestamp, string referenceNumber)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
    }
}
