// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The GenerateTokenRequest. </summary>
    public partial class GenerateTokenRequest
    {
        /// <summary> Initializes a new instance of GenerateTokenRequest. </summary>
        /// <param name="generateToken"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="generateToken"/> is null. </exception>
        public GenerateTokenRequest(GenerateTokenRequestType generateToken)
        {
            if (generateToken == null)
            {
                throw new ArgumentNullException(nameof(generateToken));
            }

            GenerateToken = generateToken;
        }

        /// <summary> Gets the generate token. </summary>
        public GenerateTokenRequestType GenerateToken { get; }
    }
}
