// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The GetPaymentIdentifierReferenceNumbersResponse. </summary>
    public partial class GetPaymentIdentifierReferenceNumbersResponse
    {
        /// <summary> Initializes a new instance of GetPaymentIdentifierReferenceNumbersResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="ksefReferenceNumberList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="ksefReferenceNumberList"/> is null. </exception>
        internal GetPaymentIdentifierReferenceNumbersResponse(DateTimeOffset timestamp, string referenceNumber, IEnumerable<string> ksefReferenceNumberList)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (ksefReferenceNumberList == null)
            {
                throw new ArgumentNullException(nameof(ksefReferenceNumberList));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            KsefReferenceNumberList = ksefReferenceNumberList.ToList();
        }

        /// <summary> Initializes a new instance of GetPaymentIdentifierReferenceNumbersResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="ksefReferenceNumberList"></param>
        internal GetPaymentIdentifierReferenceNumbersResponse(DateTimeOffset timestamp, string referenceNumber, IReadOnlyList<string> ksefReferenceNumberList)
        {
            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            KsefReferenceNumberList = ksefReferenceNumberList;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the ksef reference number list. </summary>
        public IReadOnlyList<string> KsefReferenceNumberList { get; }
    }
}
