// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class GetPaymentIdentifierReferenceNumbersResponse
    {
        internal static GetPaymentIdentifierReferenceNumbersResponse DeserializeGetPaymentIdentifierReferenceNumbersResponse(JsonElement element)
        {
            DateTimeOffset timestamp = default;
            string referenceNumber = default;
            IReadOnlyList<string> ksefReferenceNumberList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("timestamp"))
                {
                    timestamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("referenceNumber"))
                {
                    referenceNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("ksefReferenceNumberList"))
                {
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    ksefReferenceNumberList = array;
                    continue;
                }
            }
            return new GetPaymentIdentifierReferenceNumbersResponse(timestamp, referenceNumber, ksefReferenceNumberList);
        }
    }
}
