// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The GrantCredentialsRequest. </summary>
    public partial class GrantCredentialsRequest
    {
        /// <summary> Initializes a new instance of GrantCredentialsRequest. </summary>
        /// <param name="grantCredentials"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="grantCredentials"/> is null. </exception>
        public GrantCredentialsRequest(GrantCredentialsRequestType grantCredentials)
        {
            if (grantCredentials == null)
            {
                throw new ArgumentNullException(nameof(grantCredentials));
            }

            GrantCredentials = grantCredentials;
        }

        /// <summary> Gets the grant credentials. </summary>
        public GrantCredentialsRequestType GrantCredentials { get; }
    }
}
