// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The HeaderEntryType. </summary>
    public partial class HeaderEntryType
    {
        /// <summary> Initializes a new instance of HeaderEntryType. </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="key"/> or <paramref name="value"/> is null. </exception>
        internal HeaderEntryType(string key, string value)
        {
            if (key == null)
            {
                throw new ArgumentNullException(nameof(key));
            }
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Key = key;
            Value = value;
        }

        /// <summary> Gets the key. </summary>
        public string Key { get; }
        /// <summary> Gets the value. </summary>
        public string Value { get; }
    }
}
