// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The InitialisedSessionType. </summary>
    public partial class InitialisedSessionType
    {
        /// <summary> Initializes a new instance of InitialisedSessionType. </summary>
        /// <param name="token"></param>
        /// <param name="context"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="token"/> or <paramref name="context"/> is null. </exception>
        internal InitialisedSessionType(string token, SessionContextType context)
        {
            if (token == null)
            {
                throw new ArgumentNullException(nameof(token));
            }
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            Token = token;
            Context = context;
        }

        /// <summary> Gets the token. </summary>
        public string Token { get; }
        /// <summary> Gets the context. </summary>
        public SessionContextType Context { get; }
    }
}
