// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The InitSessionResponse. </summary>
    public partial class InitSessionResponse
    {
        /// <summary> Initializes a new instance of InitSessionResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="sessionToken"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="sessionToken"/> is null. </exception>
        internal InitSessionResponse(DateTimeOffset timestamp, string referenceNumber, InitialisedSessionType sessionToken)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (sessionToken == null)
            {
                throw new ArgumentNullException(nameof(sessionToken));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            SessionToken = sessionToken;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the session token. </summary>
        public InitialisedSessionType SessionToken { get; }
    }
}
