// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class InitialisedSessionType
    {
        internal static InitialisedSessionType DeserializeInitialisedSessionType(JsonElement element)
        {
            string token = default;
            SessionContextType context = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("token"))
                {
                    token = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("context"))
                {
                    context = SessionContextType.DeserializeSessionContextType(property.Value);
                    continue;
                }
            }
            return new InitialisedSessionType(token, context);
        }
    }
}
