// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The InitResponse. </summary>
    public partial class InitResponse
    {
        /// <summary> Initializes a new instance of InitResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="packageSignature"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="packageSignature"/> is null. </exception>
        internal InitResponse(DateTimeOffset timestamp, string referenceNumber, PackageSignatureInitResponseType packageSignature)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (packageSignature == null)
            {
                throw new ArgumentNullException(nameof(packageSignature));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            PackageSignature = packageSignature;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the package signature. </summary>
        public PackageSignatureInitResponseType PackageSignature { get; }
    }
}
