// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class InvoicePayloadEncryptedType : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("encryptedInvoiceHash");
            writer.WriteObjectValue(EncryptedInvoiceHash);
            writer.WritePropertyName("encryptedInvoiceBody");
            writer.WriteStringValue(EncryptedInvoiceBody);
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }
    }
}
