// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.IO;

namespace KSeFAPI.Models
{
    /// <summary> The InvoicePayloadEncryptedType. </summary>
    public partial class InvoicePayloadEncryptedType : InvoicePayloadType
    {
        /// <summary> Initializes a new instance of InvoicePayloadEncryptedType. </summary>
        /// <param name="encryptedInvoiceHash"></param>
        /// <param name="encryptedInvoiceBody"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="encryptedInvoiceHash"/> or <paramref name="encryptedInvoiceBody"/> is null. </exception>
        public InvoicePayloadEncryptedType(File2MBHashType encryptedInvoiceHash, /*Stream*/ string encryptedInvoiceBody)
        {
            if (encryptedInvoiceHash == null)
            {
                throw new ArgumentNullException(nameof(encryptedInvoiceHash));
            }
            if (encryptedInvoiceBody == null)
            {
                throw new ArgumentNullException(nameof(encryptedInvoiceBody));
            }

            EncryptedInvoiceHash = encryptedInvoiceHash;
            EncryptedInvoiceBody = encryptedInvoiceBody;
            Type = "encrypted";
        }

        /// <summary> Gets the encrypted invoice hash. </summary>
        public File2MBHashType EncryptedInvoiceHash { get; }
        /// <summary> Gets the encrypted invoice body. </summary>
        public /*Stream*/ string EncryptedInvoiceBody { get; }
    }
}
