// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class InvoiceRequestKSeF : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("ksefReferenceNumber");
            writer.WriteStringValue(KsefReferenceNumber);
            writer.WritePropertyName("invoiceDetails");
            writer.WriteObjectValue(InvoiceDetails);
            writer.WriteEndObject();
        }
    }
}
