// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The InvoiceQueryDetailsType. </summary>
    public partial class InvoiceQueryDetailsType
    {
        /// <summary> Initializes a new instance of InvoiceQueryDetailsType. </summary>
        /// <param name="subjectTo"></param>
        /// <param name="invoiceOryginalNumber"></param>
        /// <param name="dueValue"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="subjectTo"/>, <paramref name="invoiceOryginalNumber"/> or <paramref name="dueValue"/> is null. </exception>
        public InvoiceQueryDetailsType(SubjectToType subjectTo, string invoiceOryginalNumber, string dueValue)
        {
            if (subjectTo == null)
            {
                throw new ArgumentNullException(nameof(subjectTo));
            }
            if (invoiceOryginalNumber == null)
            {
                throw new ArgumentNullException(nameof(invoiceOryginalNumber));
            }
            if (dueValue == null)
            {
                throw new ArgumentNullException(nameof(dueValue));
            }

            SubjectTo = subjectTo;
            InvoiceOryginalNumber = invoiceOryginalNumber;
            DueValue = dueValue;
        }

        /// <summary> Gets the subject to. </summary>
        public SubjectToType SubjectTo { get; }
        /// <summary> Gets the invoice oryginal number. </summary>
        public string InvoiceOryginalNumber { get; }
        /// <summary> Gets the due value. </summary>
        public string DueValue { get; }
    }
}
