// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.IO;

namespace KSeFAPI.Models
{
    /// <summary> The InvoicePayloadPlainType. </summary>
    public partial class InvoicePayloadPlainType : InvoicePayloadType
    {
        /// <summary> Initializes a new instance of InvoicePayloadPlainType. </summary>
        /// <param name="invoiceBody"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="invoiceBody"/> is null. </exception>
        public InvoicePayloadPlainType(/*Stream*/ string invoiceBody)
        {
            if (invoiceBody == null)
            {
                throw new ArgumentNullException(nameof(invoiceBody));
            }

            InvoiceBody = invoiceBody;
            Type = "plain";
        }

        /// <summary> Gets the invoice body. </summary>
        public /*Stream*/ string InvoiceBody { get; }
    }
}
