// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class InvoiceQueryDetailsType : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("subjectTo");
            writer.WriteObjectValue(SubjectTo);
            writer.WritePropertyName("invoiceOryginalNumber");
            writer.WriteStringValue(InvoiceOryginalNumber);
            writer.WritePropertyName("dueValue");
            writer.WriteStringValue(DueValue);
            writer.WriteEndObject();
        }
    }
}
