// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class PackageSignatureInitResponseType
    {
        internal static PackageSignatureInitResponseType DeserializePackageSignatureInitResponseType(JsonElement element)
        {
            string packageName = default;
            IReadOnlyList<PackagePartSignatureInitResponseType> packagePartSignatureList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("packageName"))
                {
                    packageName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("packagePartSignatureList"))
                {
                    List<PackagePartSignatureInitResponseType> array = new List<PackagePartSignatureInitResponseType>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(PackagePartSignatureInitResponseType.DeserializePackagePartSignatureInitResponseType(item));
                    }
                    packagePartSignatureList = array;
                    continue;
                }
            }
            return new PackageSignatureInitResponseType(packageName, packagePartSignatureList);
        }
    }
}
