// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The PackagePartSignatureInitResponseTypeMethod. </summary>
    public readonly partial struct PackagePartSignatureInitResponseTypeMethod : IEquatable<PackagePartSignatureInitResponseTypeMethod>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="PackagePartSignatureInitResponseTypeMethod"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public PackagePartSignatureInitResponseTypeMethod(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string PostValue = "POST";
        private const string PUTValue = "PUT";

        /// <summary> POST. </summary>
        public static PackagePartSignatureInitResponseTypeMethod Post { get; } = new PackagePartSignatureInitResponseTypeMethod(PostValue);
        /// <summary> PUT. </summary>
        public static PackagePartSignatureInitResponseTypeMethod PUT { get; } = new PackagePartSignatureInitResponseTypeMethod(PUTValue);
        /// <summary> Determines if two <see cref="PackagePartSignatureInitResponseTypeMethod"/> values are the same. </summary>
        public static bool operator ==(PackagePartSignatureInitResponseTypeMethod left, PackagePartSignatureInitResponseTypeMethod right) => left.Equals(right);
        /// <summary> Determines if two <see cref="PackagePartSignatureInitResponseTypeMethod"/> values are not the same. </summary>
        public static bool operator !=(PackagePartSignatureInitResponseTypeMethod left, PackagePartSignatureInitResponseTypeMethod right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="PackagePartSignatureInitResponseTypeMethod"/>. </summary>
        public static implicit operator PackagePartSignatureInitResponseTypeMethod(string value) => new PackagePartSignatureInitResponseTypeMethod(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is PackagePartSignatureInitResponseTypeMethod other && Equals(other);
        /// <inheritdoc />
        public bool Equals(PackagePartSignatureInitResponseTypeMethod other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
