// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class PackagePartSignatureInitResponseType
    {
        internal static PackagePartSignatureInitResponseType DeserializePackagePartSignatureInitResponseType(JsonElement element)
        {
            int ordinalNumber = default;
            string partFileName = default;
            string url = default;
            PackagePartSignatureInitResponseTypeMethod method = default;
            Optional<IReadOnlyList<HeaderEntryType>> headerEntryList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("ordinalNumber"))
                {
                    ordinalNumber = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("partFileName"))
                {
                    partFileName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("url"))
                {
                    url = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("method"))
                {
                    method = new PackagePartSignatureInitResponseTypeMethod(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("headerEntryList"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<HeaderEntryType> array = new List<HeaderEntryType>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(HeaderEntryType.DeserializeHeaderEntryType(item));
                    }
                    headerEntryList = array;
                    continue;
                }
            }
            return new PackagePartSignatureInitResponseType(ordinalNumber, partFileName, url, method, Optional.ToList(headerEntryList));
        }
    }
}
