// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaInvoiceType. </summary>
    public partial class QueryCriteriaInvoiceType
    {
        /// <summary> Initializes a new instance of QueryCriteriaInvoiceType. </summary>
        /// <param name="subjectType"></param>
        public QueryCriteriaInvoiceType(QueryCriteriaInvoiceTypeSubjectType subjectType)
        {
            SubjectType = subjectType;
        }

        /// <summary> Gets the subject type. </summary>
        public QueryCriteriaInvoiceTypeSubjectType SubjectType { get; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
