// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType. </summary>
    public readonly partial struct QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType : IEquatable<QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string CurrentValue = "current";

        /// <summary> current. </summary>
        public static QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType Current { get; } = new QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType(CurrentValue);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType"/> values are the same. </summary>
        public static bool operator ==(QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType left, QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType"/> values are not the same. </summary>
        public static bool operator !=(QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType left, QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType"/>. </summary>
        public static implicit operator QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType(string value) => new QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
