// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsIdType. </summary>
    public partial class QueryCriteriaCredentialsIdType : QueryCriteriaCredentialsType
    {
        /// <summary> Initializes a new instance of QueryCriteriaCredentialsIdType. </summary>
        /// <param name="queryCredentialsTypeResultType"></param>
        /// <param name="queryCredentialsScopeResultType"></param>
        /// <param name="credentialsIdentifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="credentialsIdentifier"/> is null. </exception>
        public QueryCriteriaCredentialsIdType(QueryCriteriaCredentialsIdTypeQueryCredentialsTypeResultType queryCredentialsTypeResultType, QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType queryCredentialsScopeResultType, CredentialsIdentifierRequestType credentialsIdentifier)
        {
            if (credentialsIdentifier == null)
            {
                throw new ArgumentNullException(nameof(credentialsIdentifier));
            }

            QueryCredentialsTypeResultType = queryCredentialsTypeResultType;
            QueryCredentialsScopeResultType = queryCredentialsScopeResultType;
            CredentialsIdentifier = credentialsIdentifier;
            Type = "list_id";
        }

        /// <summary> Gets the query credentials type result type. </summary>
        public QueryCriteriaCredentialsIdTypeQueryCredentialsTypeResultType QueryCredentialsTypeResultType { get; }
        /// <summary> Gets the query credentials scope result type. </summary>
        public QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType QueryCredentialsScopeResultType { get; }
        /// <summary> Gets the credentials identifier. </summary>
        public CredentialsIdentifierRequestType CredentialsIdentifier { get; }
    }
}
