// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsType. </summary>
    public partial class QueryCriteriaCredentialsType
    {
        /// <summary> Initializes a new instance of QueryCriteriaCredentialsType. </summary>
        public QueryCriteriaCredentialsType()
        {
        }

        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
