// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The QuerySyncCredentialsResponse. </summary>
    public partial class QuerySyncCredentialsResponse
    {
        /// <summary> Initializes a new instance of QuerySyncCredentialsResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="credentialsList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="credentialsList"/> is null. </exception>
        internal QuerySyncCredentialsResponse(DateTimeOffset timestamp, string referenceNumber, IEnumerable<CredentialsBaseTypeObject> credentialsList)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (credentialsList == null)
            {
                throw new ArgumentNullException(nameof(credentialsList));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            CredentialsList = credentialsList.ToList();
        }

        /// <summary> Initializes a new instance of QuerySyncCredentialsResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="credentialsList"></param>
        internal QuerySyncCredentialsResponse(DateTimeOffset timestamp, string referenceNumber, IReadOnlyList<CredentialsBaseTypeObject> credentialsList)
        {
            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            CredentialsList = credentialsList;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the credentials list. </summary>
        public IReadOnlyList<CredentialsBaseTypeObject> CredentialsList { get; }
    }
}
