// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaInvoiceDetailType. </summary>
    public partial class QueryCriteriaInvoiceDetailType : QueryCriteriaInvoiceType
    {
        /// <summary> Initializes a new instance of QueryCriteriaInvoiceDetailType. </summary>
        /// <param name="subjectType"></param>
        /// <param name="invoicingDateFrom"></param>
        /// <param name="invoicingDateTo"></param>
        public QueryCriteriaInvoiceDetailType(QueryCriteriaInvoiceTypeSubjectType subjectType, DateTimeOffset invoicingDateFrom, DateTimeOffset invoicingDateTo) : base(subjectType)
        {
            InvoicingDateFrom = invoicingDateFrom;
            InvoicingDateTo = invoicingDateTo;
            Type = "detail";
        }

        /// <summary> Gets or sets the invoice number. </summary>
        public string InvoiceNumber { get; set; }
        /// <summary> Gets or sets the ksef reference number. </summary>
        public string KsefReferenceNumber { get; set; }
        /// <summary> Gets the invoicing date from. </summary>
        public DateTimeOffset InvoicingDateFrom { get; }
        /// <summary> Gets the invoicing date to. </summary>
        public DateTimeOffset InvoicingDateTo { get; }
        /// <summary> Gets or sets the subject by. </summary>
        public SubjectByType SubjectBy { get; set; }
        /// <summary> Gets or sets the subject to. </summary>
        public SubjectToType SubjectTo { get; set; }
    }
}
