// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaInvoiceRangeType. </summary>
    public partial class QueryCriteriaInvoiceRangeType : QueryCriteriaInvoiceType
    {
        /// <summary> Initializes a new instance of QueryCriteriaInvoiceRangeType. </summary>
        /// <param name="subjectType"></param>
        /// <param name="invoicingDateFrom"></param>
        /// <param name="invoicingDateTo"></param>
        public QueryCriteriaInvoiceRangeType(QueryCriteriaInvoiceTypeSubjectType subjectType, DateTimeOffset invoicingDateFrom, DateTimeOffset invoicingDateTo) : base(subjectType)
        {
            InvoicingDateFrom = invoicingDateFrom;
            InvoicingDateTo = invoicingDateTo;
            Type = "range";
        }

        /// <summary> Gets the invoicing date from. </summary>
        public DateTimeOffset InvoicingDateFrom { get; }
        /// <summary> Gets the invoicing date to. </summary>
        public DateTimeOffset InvoicingDateTo { get; }
    }
}
