// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class QueryCriteriaInvoiceDetailType : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(InvoiceNumber))
            {
                writer.WritePropertyName("invoiceNumber");
                writer.WriteStringValue(InvoiceNumber);
            }
            if (Optional.IsDefined(KsefReferenceNumber))
            {
                writer.WritePropertyName("ksefReferenceNumber");
                writer.WriteStringValue(KsefReferenceNumber);
            }
            writer.WritePropertyName("invoicingDateFrom");
            writer.WriteStringValue(InvoicingDateFrom, "O");
            writer.WritePropertyName("invoicingDateTo");
            writer.WriteStringValue(InvoicingDateTo, "O");
            if (Optional.IsDefined(SubjectBy))
            {
                writer.WritePropertyName("subjectBy");
                writer.WriteObjectValue(SubjectBy);
            }
            if (Optional.IsDefined(SubjectTo))
            {
                writer.WritePropertyName("subjectTo");
                writer.WriteObjectValue(SubjectTo);
            }
            writer.WritePropertyName("subjectType");
            writer.WriteStringValue(SubjectType.ToString());
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }
    }
}
