// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The QueryInvoiceSyncResponse. </summary>
    public partial class QueryInvoiceSyncResponse
    {
        /// <summary> Initializes a new instance of QueryInvoiceSyncResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="numberOfElements"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageOffset"></param>
        /// <param name="invoiceHeaderList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="invoiceHeaderList"/> is null. </exception>
        internal QueryInvoiceSyncResponse(DateTimeOffset timestamp, string referenceNumber, long numberOfElements, int pageSize, int pageOffset, IEnumerable<InvoiceHeaderType> invoiceHeaderList)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (invoiceHeaderList == null)
            {
                throw new ArgumentNullException(nameof(invoiceHeaderList));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            NumberOfElements = numberOfElements;
            PageSize = pageSize;
            PageOffset = pageOffset;
            InvoiceHeaderList = invoiceHeaderList.ToList();
        }

        /// <summary> Initializes a new instance of QueryInvoiceSyncResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="numberOfElements"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageOffset"></param>
        /// <param name="invoiceHeaderList"></param>
        internal QueryInvoiceSyncResponse(DateTimeOffset timestamp, string referenceNumber, long numberOfElements, int pageSize, int pageOffset, IReadOnlyList<InvoiceHeaderType> invoiceHeaderList)
        {
            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            NumberOfElements = numberOfElements;
            PageSize = pageSize;
            PageOffset = pageOffset;
            InvoiceHeaderList = invoiceHeaderList;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the number of elements. </summary>
        public long NumberOfElements { get; }
        /// <summary> Gets the page size. </summary>
        public int PageSize { get; }
        /// <summary> Gets the page offset. </summary>
        public int PageOffset { get; }
        /// <summary> Gets the invoice header list. </summary>
        public IReadOnlyList<InvoiceHeaderType> InvoiceHeaderList { get; }
    }
}
