// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The QueryInvoiceAsyncInitResponse. </summary>
    public partial class QueryInvoiceAsyncInitResponse
    {
        /// <summary> Initializes a new instance of QueryInvoiceAsyncInitResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="processingCode"></param>
        /// <param name="processingDescription"></param>
        /// <param name="elementReferenceNumber"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/>, <paramref name="processingDescription"/> or <paramref name="elementReferenceNumber"/> is null. </exception>
        internal QueryInvoiceAsyncInitResponse(DateTimeOffset timestamp, string referenceNumber, int processingCode, string processingDescription, string elementReferenceNumber)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (processingDescription == null)
            {
                throw new ArgumentNullException(nameof(processingDescription));
            }
            if (elementReferenceNumber == null)
            {
                throw new ArgumentNullException(nameof(elementReferenceNumber));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            ProcessingCode = processingCode;
            ProcessingDescription = processingDescription;
            ElementReferenceNumber = elementReferenceNumber;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the processing code. </summary>
        public int ProcessingCode { get; }
        /// <summary> Gets the processing description. </summary>
        public string ProcessingDescription { get; }
        /// <summary> Gets the element reference number. </summary>
        public string ElementReferenceNumber { get; }
    }
}
