// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsAllType. </summary>
    public partial class QueryCriteriaCredentialsAllType : QueryCriteriaCredentialsType
    {
        /// <summary> Initializes a new instance of QueryCriteriaCredentialsAllType. </summary>
        /// <param name="queryCredentialsTypeResultType"></param>
        /// <param name="queryCredentialsScopeResultType"></param>
        public QueryCriteriaCredentialsAllType(QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType queryCredentialsTypeResultType, QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType queryCredentialsScopeResultType)
        {
            QueryCredentialsTypeResultType = queryCredentialsTypeResultType;
            QueryCredentialsScopeResultType = queryCredentialsScopeResultType;
            Type = "list_all";
        }

        /// <summary> Gets the query credentials type result type. </summary>
        public QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType QueryCredentialsTypeResultType { get; }
        /// <summary> Gets the query credentials scope result type. </summary>
        public QueryCriteriaCredentialsAllTypeQueryCredentialsScopeResultType QueryCredentialsScopeResultType { get; }
    }
}
