// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType. </summary>
    public readonly partial struct QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType : IEquatable<QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string AllValue = "all";
        private const string StandardValue = "standard";
        private const string TokenValue = "token";

        /// <summary> all. </summary>
        public static QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType All { get; } = new QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(AllValue);
        /// <summary> standard. </summary>
        public static QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType Standard { get; } = new QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(StandardValue);
        /// <summary> token. </summary>
        public static QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType Token { get; } = new QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(TokenValue);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType"/> values are the same. </summary>
        public static bool operator ==(QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType left, QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType"/> values are not the same. </summary>
        public static bool operator !=(QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType left, QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType"/>. </summary>
        public static implicit operator QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(string value) => new QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(QueryCriteriaCredentialsAllTypeQueryCredentialsTypeResultType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
