// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaInvoiceTypeSubjectType. </summary>
    public readonly partial struct QueryCriteriaInvoiceTypeSubjectType : IEquatable<QueryCriteriaInvoiceTypeSubjectType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="QueryCriteriaInvoiceTypeSubjectType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public QueryCriteriaInvoiceTypeSubjectType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string Subject1Value = "subject1";
        private const string Subject2Value = "subject2";
        private const string Subject3Value = "subject3";
        private const string SubjectAuthorizedValue = "subjectAuthorized";

        /// <summary> subject1. </summary>
        public static QueryCriteriaInvoiceTypeSubjectType Subject1 { get; } = new QueryCriteriaInvoiceTypeSubjectType(Subject1Value);
        /// <summary> subject2. </summary>
        public static QueryCriteriaInvoiceTypeSubjectType Subject2 { get; } = new QueryCriteriaInvoiceTypeSubjectType(Subject2Value);
        /// <summary> subject3. </summary>
        public static QueryCriteriaInvoiceTypeSubjectType Subject3 { get; } = new QueryCriteriaInvoiceTypeSubjectType(Subject3Value);
        /// <summary> subjectAuthorized. </summary>
        public static QueryCriteriaInvoiceTypeSubjectType SubjectAuthorized { get; } = new QueryCriteriaInvoiceTypeSubjectType(SubjectAuthorizedValue);
        /// <summary> Determines if two <see cref="QueryCriteriaInvoiceTypeSubjectType"/> values are the same. </summary>
        public static bool operator ==(QueryCriteriaInvoiceTypeSubjectType left, QueryCriteriaInvoiceTypeSubjectType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="QueryCriteriaInvoiceTypeSubjectType"/> values are not the same. </summary>
        public static bool operator !=(QueryCriteriaInvoiceTypeSubjectType left, QueryCriteriaInvoiceTypeSubjectType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="QueryCriteriaInvoiceTypeSubjectType"/>. </summary>
        public static implicit operator QueryCriteriaInvoiceTypeSubjectType(string value) => new QueryCriteriaInvoiceTypeSubjectType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is QueryCriteriaInvoiceTypeSubjectType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(QueryCriteriaInvoiceTypeSubjectType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
