// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class QueryInvoiceSyncResponse
    {
        internal static QueryInvoiceSyncResponse DeserializeQueryInvoiceSyncResponse(JsonElement element)
        {
            DateTimeOffset timestamp = default;
            string referenceNumber = default;
            long numberOfElements = default;
            int pageSize = default;
            int pageOffset = default;
            IReadOnlyList<InvoiceHeaderType> invoiceHeaderList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("timestamp"))
                {
                    timestamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("referenceNumber"))
                {
                    referenceNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("numberOfElements"))
                {
                    numberOfElements = property.Value.GetInt64();
                    continue;
                }
                if (property.NameEquals("pageSize"))
                {
                    pageSize = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("pageOffset"))
                {
                    pageOffset = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("invoiceHeaderList"))
                {
                    List<InvoiceHeaderType> array = new List<InvoiceHeaderType>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(InvoiceHeaderType.DeserializeInvoiceHeaderType(item));
                    }
                    invoiceHeaderList = array;
                    continue;
                }
            }
            return new QueryInvoiceSyncResponse(timestamp, referenceNumber, numberOfElements, pageSize, pageOffset, invoiceHeaderList);
        }
    }
}
