// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace KSeFAPI.Models
{
    /// <summary> The QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType. </summary>
    public readonly partial struct QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType : IEquatable<QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string CurrentValue = "current";

        /// <summary> current. </summary>
        public static QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType Current { get; } = new QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType(CurrentValue);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType"/> values are the same. </summary>
        public static bool operator ==(QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType left, QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType"/> values are not the same. </summary>
        public static bool operator !=(QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType left, QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType"/>. </summary>
        public static implicit operator QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType(string value) => new QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(QueryCriteriaCredentialsIdTypeQueryCredentialsScopeResultType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
