// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The RequestPaymentIdentifierResponse. </summary>
    public partial class RequestPaymentIdentifierResponse
    {
        /// <summary> Initializes a new instance of RequestPaymentIdentifierResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="paymentIdentifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/> or <paramref name="paymentIdentifier"/> is null. </exception>
        internal RequestPaymentIdentifierResponse(DateTimeOffset timestamp, string referenceNumber, string paymentIdentifier)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (paymentIdentifier == null)
            {
                throw new ArgumentNullException(nameof(paymentIdentifier));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            PaymentIdentifier = paymentIdentifier;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the payment identifier. </summary>
        public string PaymentIdentifier { get; }
    }
}
