// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The RequestPaymentIdentifierRequest. </summary>
    public partial class RequestPaymentIdentifierRequest
    {
        /// <summary> Initializes a new instance of RequestPaymentIdentifierRequest. </summary>
        /// <param name="ksefReferenceNumberList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="ksefReferenceNumberList"/> is null. </exception>
        public RequestPaymentIdentifierRequest(IEnumerable<string> ksefReferenceNumberList)
        {
            if (ksefReferenceNumberList == null)
            {
                throw new ArgumentNullException(nameof(ksefReferenceNumberList));
            }

            KsefReferenceNumberList = ksefReferenceNumberList.ToList();
        }

        /// <summary> Gets the ksef reference number list. </summary>
        public IList<string> KsefReferenceNumberList { get; }
    }
}
