// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class RequestPaymentIdentifierResponse
    {
        internal static RequestPaymentIdentifierResponse DeserializeRequestPaymentIdentifierResponse(JsonElement element)
        {
            DateTimeOffset timestamp = default;
            string referenceNumber = default;
            string paymentIdentifier = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("timestamp"))
                {
                    timestamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("referenceNumber"))
                {
                    referenceNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("paymentIdentifier"))
                {
                    paymentIdentifier = property.Value.GetString();
                    continue;
                }
            }
            return new RequestPaymentIdentifierResponse(timestamp, referenceNumber, paymentIdentifier);
        }
    }
}
