// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The RevokeTokenRequest. </summary>
    public partial class RevokeTokenRequest
    {
        /// <summary> Initializes a new instance of RevokeTokenRequest. </summary>
        /// <param name="revokeToken"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="revokeToken"/> is null. </exception>
        public RevokeTokenRequest(RevokeTokenRequestType revokeToken)
        {
            if (revokeToken == null)
            {
                throw new ArgumentNullException(nameof(revokeToken));
            }

            RevokeToken = revokeToken;
        }

        /// <summary> Gets the revoke token. </summary>
        public RevokeTokenRequestType RevokeToken { get; }
    }
}
