// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The RevokeCredentialsRequestType. </summary>
    public partial class RevokeCredentialsRequestType
    {
        /// <summary> Initializes a new instance of RevokeCredentialsRequestType. </summary>
        /// <param name="credentialsIdentifier"></param>
        /// <param name="description"></param>
        /// <param name="credentialsRoleList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="credentialsIdentifier"/>, <paramref name="description"/> or <paramref name="credentialsRoleList"/> is null. </exception>
        public RevokeCredentialsRequestType(CredentialsIdentifierRequestType credentialsIdentifier, string description, IEnumerable<CredentialsRoleRequestStandardBaseType> credentialsRoleList)
        {
            if (credentialsIdentifier == null)
            {
                throw new ArgumentNullException(nameof(credentialsIdentifier));
            }
            if (description == null)
            {
                throw new ArgumentNullException(nameof(description));
            }
            if (credentialsRoleList == null)
            {
                throw new ArgumentNullException(nameof(credentialsRoleList));
            }

            CredentialsIdentifier = credentialsIdentifier;
            Description = description;
            CredentialsRoleList = credentialsRoleList.ToList();
        }

        /// <summary> Gets the credentials identifier. </summary>
        public CredentialsIdentifierRequestType CredentialsIdentifier { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> Gets the credentials role list. </summary>
        public IList<CredentialsRoleRequestStandardBaseType> CredentialsRoleList { get; }
    }
}
