// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The RevokeCredentialsRequest. </summary>
    public partial class RevokeCredentialsRequest
    {
        /// <summary> Initializes a new instance of RevokeCredentialsRequest. </summary>
        /// <param name="revokeCredentials"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="revokeCredentials"/> is null. </exception>
        public RevokeCredentialsRequest(RevokeCredentialsRequestType revokeCredentials)
        {
            if (revokeCredentials == null)
            {
                throw new ArgumentNullException(nameof(revokeCredentials));
            }

            RevokeCredentials = revokeCredentials;
        }

        /// <summary> Gets the revoke credentials. </summary>
        public RevokeCredentialsRequestType RevokeCredentials { get; }
    }
}
