// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The RevokeTokenRequestType. </summary>
    public partial class RevokeTokenRequestType
    {
        /// <summary> Initializes a new instance of RevokeTokenRequestType. </summary>
        /// <param name="sourceTokenIdentifier"></param>
        /// <param name="tokenNumber"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="sourceTokenIdentifier"/> or <paramref name="tokenNumber"/> is null. </exception>
        public RevokeTokenRequestType(CredentialsIdentifierRequestType sourceTokenIdentifier, string tokenNumber)
        {
            if (sourceTokenIdentifier == null)
            {
                throw new ArgumentNullException(nameof(sourceTokenIdentifier));
            }
            if (tokenNumber == null)
            {
                throw new ArgumentNullException(nameof(tokenNumber));
            }

            SourceTokenIdentifier = sourceTokenIdentifier;
            TokenNumber = tokenNumber;
        }

        /// <summary> Gets the source token identifier. </summary>
        public CredentialsIdentifierRequestType SourceTokenIdentifier { get; }
        /// <summary> Gets the token number. </summary>
        public string TokenNumber { get; }
    }
}
