// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SendInvoiceRequest. </summary>
    public partial class SendInvoiceRequest
    {
        /// <summary> Initializes a new instance of SendInvoiceRequest. </summary>
        /// <param name="invoiceHash"></param>
        /// <param name="invoicePayload"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="invoiceHash"/> or <paramref name="invoicePayload"/> is null. </exception>
        public SendInvoiceRequest(File1MBHashType invoiceHash, InvoicePayloadType invoicePayload)
        {
            if (invoiceHash == null)
            {
                throw new ArgumentNullException(nameof(invoiceHash));
            }
            if (invoicePayload == null)
            {
                throw new ArgumentNullException(nameof(invoicePayload));
            }

            InvoiceHash = invoiceHash;
            InvoicePayload = invoicePayload;
        }

        /// <summary> Gets the invoice hash. </summary>
        public File1MBHashType InvoiceHash { get; }
        /// <summary> Gets the invoice payload. </summary>
        public InvoicePayloadType InvoicePayload { get; }
    }
}
