// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SessionInvoiceStatusType. </summary>
    public partial class SessionInvoiceStatusType
    {
        /// <summary> Initializes a new instance of SessionInvoiceStatusType. </summary>
        /// <param name="processingCode"></param>
        /// <param name="processingDescription"></param>
        /// <param name="elementReferenceNumber"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="processingDescription"/> or <paramref name="elementReferenceNumber"/> is null. </exception>
        internal SessionInvoiceStatusType(int processingCode, string processingDescription, string elementReferenceNumber)
        {
            if (processingDescription == null)
            {
                throw new ArgumentNullException(nameof(processingDescription));
            }
            if (elementReferenceNumber == null)
            {
                throw new ArgumentNullException(nameof(elementReferenceNumber));
            }

            ProcessingCode = processingCode;
            ProcessingDescription = processingDescription;
            ElementReferenceNumber = elementReferenceNumber;
        }

        /// <summary> Initializes a new instance of SessionInvoiceStatusType. </summary>
        /// <param name="processingCode"></param>
        /// <param name="processingDescription"></param>
        /// <param name="elementReferenceNumber"></param>
        /// <param name="invoiceNumber"></param>
        /// <param name="ksefReferenceNumber"></param>
        /// <param name="acquisitionTimestamp"></param>
        internal SessionInvoiceStatusType(int processingCode, string processingDescription, string elementReferenceNumber, string invoiceNumber, string ksefReferenceNumber, DateTimeOffset? acquisitionTimestamp)
        {
            ProcessingCode = processingCode;
            ProcessingDescription = processingDescription;
            ElementReferenceNumber = elementReferenceNumber;
            InvoiceNumber = invoiceNumber;
            KsefReferenceNumber = ksefReferenceNumber;
            AcquisitionTimestamp = acquisitionTimestamp;
        }

        /// <summary> Gets the processing code. </summary>
        public int ProcessingCode { get; }
        /// <summary> Gets the processing description. </summary>
        public string ProcessingDescription { get; }
        /// <summary> Gets the element reference number. </summary>
        public string ElementReferenceNumber { get; }
        /// <summary> Gets the invoice number. </summary>
        public string InvoiceNumber { get; }
        /// <summary> Gets the ksef reference number. </summary>
        public string KsefReferenceNumber { get; }
        /// <summary> Gets the acquisition timestamp. </summary>
        public DateTimeOffset? AcquisitionTimestamp { get; }
    }
}
