// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class SessionContextType
    {
        internal static SessionContextType DeserializeSessionContextType(JsonElement element)
        {
            SubjectIdentifierByType contextIdentifier = default;
            Optional<SubjectNameType> contextName = default;
            IReadOnlyList<CredentialsRoleResponseBaseTypeObject> credentialsRoleList = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("contextIdentifier"))
                {
                    contextIdentifier = SubjectIdentifierByType.DeserializeSubjectIdentifierByType(property.Value);
                    continue;
                }
                if (property.NameEquals("contextName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    contextName = SubjectNameType.DeserializeSubjectNameType(property.Value);
                    continue;
                }
                if (property.NameEquals("credentialsRoleList"))
                {
                    List<CredentialsRoleResponseBaseTypeObject> array = new List<CredentialsRoleResponseBaseTypeObject>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(CredentialsRoleResponseBaseTypeObject.DeserializeCredentialsRoleResponseBaseTypeObject(item));
                    }
                    credentialsRoleList = array;
                    continue;
                }
            }
            return new SessionContextType(contextIdentifier, contextName.Value, credentialsRoleList);
        }
    }
}
