// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace KSeFAPI.Models
{
    /// <summary> The SessionStatusResponse. </summary>
    public partial class SessionStatusResponse
    {
        /// <summary> Initializes a new instance of SessionStatusResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="numberOfElements"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageOffset"></param>
        /// <param name="processingCode"></param>
        /// <param name="processingDescription"></param>
        /// <param name="invoiceStatusList"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="referenceNumber"/>, <paramref name="processingDescription"/> or <paramref name="invoiceStatusList"/> is null. </exception>
        internal SessionStatusResponse(DateTimeOffset timestamp, string referenceNumber, long numberOfElements, int pageSize, int pageOffset, int processingCode, string processingDescription, IEnumerable<SessionInvoiceStatusType> invoiceStatusList)
        {
            if (referenceNumber == null)
            {
                throw new ArgumentNullException(nameof(referenceNumber));
            }
            if (processingDescription == null)
            {
                throw new ArgumentNullException(nameof(processingDescription));
            }
            if (invoiceStatusList == null)
            {
                throw new ArgumentNullException(nameof(invoiceStatusList));
            }

            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            NumberOfElements = numberOfElements;
            PageSize = pageSize;
            PageOffset = pageOffset;
            ProcessingCode = processingCode;
            ProcessingDescription = processingDescription;
            InvoiceStatusList = invoiceStatusList.ToList();
        }

        /// <summary> Initializes a new instance of SessionStatusResponse. </summary>
        /// <param name="timestamp"></param>
        /// <param name="referenceNumber"></param>
        /// <param name="numberOfElements"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageOffset"></param>
        /// <param name="processingCode"></param>
        /// <param name="processingDescription"></param>
        /// <param name="invoiceStatusList"></param>
        internal SessionStatusResponse(DateTimeOffset timestamp, string referenceNumber, long numberOfElements, int pageSize, int pageOffset, int processingCode, string processingDescription, IReadOnlyList<SessionInvoiceStatusType> invoiceStatusList)
        {
            Timestamp = timestamp;
            ReferenceNumber = referenceNumber;
            NumberOfElements = numberOfElements;
            PageSize = pageSize;
            PageOffset = pageOffset;
            ProcessingCode = processingCode;
            ProcessingDescription = processingDescription;
            InvoiceStatusList = invoiceStatusList;
        }

        /// <summary> Gets the timestamp. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Gets the reference number. </summary>
        public string ReferenceNumber { get; }
        /// <summary> Gets the number of elements. </summary>
        public long NumberOfElements { get; }
        /// <summary> Gets the page size. </summary>
        public int PageSize { get; }
        /// <summary> Gets the page offset. </summary>
        public int PageOffset { get; }
        /// <summary> Gets the processing code. </summary>
        public int ProcessingCode { get; }
        /// <summary> Gets the processing description. </summary>
        public string ProcessingDescription { get; }
        /// <summary> Gets the invoice status list. </summary>
        public IReadOnlyList<SessionInvoiceStatusType> InvoiceStatusList { get; }
    }
}
