// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class StatusCredentialsResponse
    {
        internal static StatusCredentialsResponse DeserializeStatusCredentialsResponse(JsonElement element)
        {
            DateTimeOffset timestamp = default;
            string referenceNumber = default;
            int processingCode = default;
            string processingDescription = default;
            string elementReferenceNumber = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("timestamp"))
                {
                    timestamp = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("referenceNumber"))
                {
                    referenceNumber = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("processingCode"))
                {
                    processingCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("processingDescription"))
                {
                    processingDescription = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("elementReferenceNumber"))
                {
                    elementReferenceNumber = property.Value.GetString();
                    continue;
                }
            }
            return new StatusCredentialsResponse(timestamp, referenceNumber, processingCode, processingDescription, elementReferenceNumber);
        }
    }
}
