// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectFullNameType. </summary>
    public partial class SubjectFullNameType : SubjectNameType
    {
        /// <summary> Initializes a new instance of SubjectFullNameType. </summary>
        /// <param name="fullName"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="fullName"/> is null. </exception>
        public SubjectFullNameType(string fullName)
        {
            if (fullName == null)
            {
                throw new ArgumentNullException(nameof(fullName));
            }

            FullName = fullName;
            Type = "fn";
        }

        /// <summary> Initializes a new instance of SubjectFullNameType. </summary>
        /// <param name="tradeName"></param>
        /// <param name="type"></param>
        /// <param name="fullName"></param>
        internal SubjectFullNameType(string tradeName, string type, string fullName) : base(tradeName, type)
        {
            FullName = fullName;
            Type = type ?? "fn";
        }

        /// <summary> Gets or sets the full name. </summary>
        public string FullName { get; set; }
    }
}
