// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectByType. </summary>
    public partial class SubjectByType
    {
        /// <summary> Initializes a new instance of SubjectByType. </summary>
        /// <param name="issuedByIdentifier"></param>
        /// <param name="issuedByName"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="issuedByIdentifier"/> or <paramref name="issuedByName"/> is null. </exception>
        public SubjectByType(SubjectIdentifierByType issuedByIdentifier, SubjectNameType issuedByName)
        {
            if (issuedByIdentifier == null)
            {
                throw new ArgumentNullException(nameof(issuedByIdentifier));
            }
            if (issuedByName == null)
            {
                throw new ArgumentNullException(nameof(issuedByName));
            }

            IssuedByIdentifier = issuedByIdentifier;
            IssuedByName = issuedByName;
        }

        /// <summary> Gets or sets the issued by identifier. </summary>
        public SubjectIdentifierByType IssuedByIdentifier { get; set; }
        /// <summary> Gets or sets the issued by name. </summary>
        public SubjectNameType IssuedByName { get; set; }
    }
}
