// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectPersonNameType. </summary>
    public partial class SubjectPersonNameType : SubjectNameType
    {
        /// <summary> Initializes a new instance of SubjectPersonNameType. </summary>
        /// <param name="firstName"></param>
        /// <param name="surname"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="firstName"/> or <paramref name="surname"/> is null. </exception>
        public SubjectPersonNameType(string firstName, string surname)
        {
            if (firstName == null)
            {
                throw new ArgumentNullException(nameof(firstName));
            }
            if (surname == null)
            {
                throw new ArgumentNullException(nameof(surname));
            }

            FirstName = firstName;
            Surname = surname;
            Type = "pn";
        }

        /// <summary> Initializes a new instance of SubjectPersonNameType. </summary>
        /// <param name="tradeName"></param>
        /// <param name="type"></param>
        /// <param name="firstName"></param>
        /// <param name="surname"></param>
        internal SubjectPersonNameType(string tradeName, string type, string firstName, string surname) : base(tradeName, type)
        {
            FirstName = firstName;
            Surname = surname;
            Type = type ?? "pn";
        }

        /// <summary> Gets or sets the first name. </summary>
        public string FirstName { get; set; }
        /// <summary> Gets or sets the surname. </summary>
        public string Surname { get; set; }
    }
}
