// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class SubjectPersonNameType : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("firstName");
            writer.WriteStringValue(FirstName);
            writer.WritePropertyName("surname");
            writer.WriteStringValue(Surname);
            if (Optional.IsDefined(TradeName))
            {
                writer.WritePropertyName("tradeName");
                writer.WriteStringValue(TradeName);
            }
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }

        internal static SubjectPersonNameType DeserializeSubjectPersonNameType(JsonElement element)
        {
            string firstName = default;
            string surname = default;
            Optional<string> tradeName = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("firstName"))
                {
                    firstName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("surname"))
                {
                    surname = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("tradeName"))
                {
                    tradeName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new SubjectPersonNameType(tradeName.Value, type, firstName, surname);
        }
    }
}
