// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class SubjectAuthorizedType
    {
        internal static SubjectAuthorizedType DeserializeSubjectAuthorizedType(JsonElement element)
        {
            SubjectIdentifierToType issuedToIdentifier = default;
            Optional<SubjectNameType> issuedToName = default;
            SubjectAuthorizedTypeSubjectAuthorizedType subjectAuthorizedType = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("issuedToIdentifier"))
                {
                    issuedToIdentifier = SubjectIdentifierToType.DeserializeSubjectIdentifierToType(property.Value);
                    continue;
                }
                if (property.NameEquals("issuedToName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    issuedToName = SubjectNameType.DeserializeSubjectNameType(property.Value);
                    continue;
                }
                if (property.NameEquals("subjectAuthorizedType"))
                {
                    subjectAuthorizedType = new SubjectAuthorizedTypeSubjectAuthorizedType(property.Value.GetString());
                    continue;
                }
            }
            return new SubjectAuthorizedType(issuedToIdentifier, issuedToName.Value, subjectAuthorizedType);
        }
    }
}
