// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectToType. </summary>
    public partial class SubjectToType
    {
        /// <summary> Initializes a new instance of SubjectToType. </summary>
        /// <param name="issuedToIdentifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="issuedToIdentifier"/> is null. </exception>
        public SubjectToType(SubjectIdentifierToType issuedToIdentifier)
        {
            if (issuedToIdentifier == null)
            {
                throw new ArgumentNullException(nameof(issuedToIdentifier));
            }

            IssuedToIdentifier = issuedToIdentifier;
        }

        /// <summary> Initializes a new instance of SubjectToType. </summary>
        /// <param name="issuedToIdentifier"></param>
        /// <param name="issuedToName"></param>
        internal SubjectToType(SubjectIdentifierToType issuedToIdentifier, SubjectNameType issuedToName)
        {
            IssuedToIdentifier = issuedToIdentifier;
            IssuedToName = issuedToName;
        }

        /// <summary> Gets or sets the issued to identifier. </summary>
        public SubjectIdentifierToType IssuedToIdentifier { get; set; }
        /// <summary> Gets or sets the issued to name. </summary>
        public SubjectNameType IssuedToName { get; set; }
    }
}
