// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The SubjectNameType. </summary>
    public partial class SubjectNameType
    {
        /// <summary> Initializes a new instance of SubjectNameType. </summary>
        public SubjectNameType()
        {
        }

        /// <summary> Initializes a new instance of SubjectNameType. </summary>
        /// <param name="tradeName"></param>
        /// <param name="type"></param>
        internal SubjectNameType(string tradeName, string type)
        {
            TradeName = tradeName;
            Type = type;
        }

        /// <summary> Gets or sets the trade name. </summary>
        public string TradeName { get; set; }
        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
