// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The SubjectIdentifierToNoneType. </summary>
    public partial class SubjectIdentifierToNoneType : SubjectIdentifierToType
    {
        /// <summary> Initializes a new instance of SubjectIdentifierToNoneType. </summary>
        public SubjectIdentifierToNoneType()
        {
            Type = "none";
        }

        /// <summary> Initializes a new instance of SubjectIdentifierToNoneType. </summary>
        /// <param name="type"></param>
        internal SubjectIdentifierToNoneType(string type) : base(type)
        {
            Type = type ?? "none";
        }
    }
}
