// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KSeFAPI.Models
{
    /// <summary> The SubjectIdentifierToType. </summary>
    public partial class SubjectIdentifierToType
    {
        /// <summary> Initializes a new instance of SubjectIdentifierToType. </summary>
        public SubjectIdentifierToType()
        {
        }

        /// <summary> Initializes a new instance of SubjectIdentifierToType. </summary>
        /// <param name="type"></param>
        internal SubjectIdentifierToType(string type)
        {
            Type = type;
        }

        /// <summary> Gets or sets the type. </summary>
        internal string Type { get; set; }
    }
}
