// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectIdentifierToOtherTaxType. </summary>
    public partial class SubjectIdentifierToOtherTaxType : SubjectIdentifierToType
    {
        /// <summary> Initializes a new instance of SubjectIdentifierToOtherTaxType. </summary>
        /// <param name="identifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/> is null. </exception>
        public SubjectIdentifierToOtherTaxType(string identifier)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }

            Identifier = identifier;
            Type = "other";
        }

        /// <summary> Initializes a new instance of SubjectIdentifierToOtherTaxType. </summary>
        /// <param name="type"></param>
        /// <param name="identifier"></param>
        internal SubjectIdentifierToOtherTaxType(string type, string identifier) : base(type)
        {
            Identifier = identifier;
            Type = type ?? "other";
        }

        /// <summary> Gets or sets the identifier. </summary>
        public string Identifier { get; set; }
    }
}
