// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KSeFAPI.Models
{
    public partial class SubjectFullNameType : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("fullName");
            writer.WriteStringValue(FullName);
            if (Optional.IsDefined(TradeName))
            {
                writer.WritePropertyName("tradeName");
                writer.WriteStringValue(TradeName);
            }
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }

        internal static SubjectFullNameType DeserializeSubjectFullNameType(JsonElement element)
        {
            string fullName = default;
            Optional<string> tradeName = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("fullName"))
                {
                    fullName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("tradeName"))
                {
                    tradeName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new SubjectFullNameType(tradeName.Value, type, fullName);
        }
    }
}
