// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectAuthorizedType. </summary>
    public partial class SubjectAuthorizedType
    {
        /// <summary> Initializes a new instance of SubjectAuthorizedType. </summary>
        /// <param name="issuedToIdentifier"></param>
        /// <param name="subjectAuthorizedTypeValue"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="issuedToIdentifier"/> is null. </exception>
        internal SubjectAuthorizedType(SubjectIdentifierToType issuedToIdentifier, SubjectAuthorizedTypeSubjectAuthorizedType subjectAuthorizedTypeValue)
        {
            if (issuedToIdentifier == null)
            {
                throw new ArgumentNullException(nameof(issuedToIdentifier));
            }

            IssuedToIdentifier = issuedToIdentifier;
            SubjectAuthorizedTypeValue = subjectAuthorizedTypeValue;
        }

        /// <summary> Initializes a new instance of SubjectAuthorizedType. </summary>
        /// <param name="issuedToIdentifier"></param>
        /// <param name="issuedToName"></param>
        /// <param name="subjectAuthorizedTypeValue"></param>
        internal SubjectAuthorizedType(SubjectIdentifierToType issuedToIdentifier, SubjectNameType issuedToName, SubjectAuthorizedTypeSubjectAuthorizedType subjectAuthorizedTypeValue)
        {
            IssuedToIdentifier = issuedToIdentifier;
            IssuedToName = issuedToName;
            SubjectAuthorizedTypeValue = subjectAuthorizedTypeValue;
        }

        /// <summary> Gets the issued to identifier. </summary>
        public SubjectIdentifierToType IssuedToIdentifier { get; }
        /// <summary> Gets the issued to name. </summary>
        public SubjectNameType IssuedToName { get; }
        /// <summary> Gets the subject authorized type value. </summary>
        public SubjectAuthorizedTypeSubjectAuthorizedType SubjectAuthorizedTypeValue { get; }
    }
}
