// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KSeFAPI.Models
{
    /// <summary> The SubjectIdentifierToCompanyType. </summary>
    public partial class SubjectIdentifierToCompanyType : SubjectIdentifierToType
    {
        /// <summary> Initializes a new instance of SubjectIdentifierToCompanyType. </summary>
        /// <param name="identifier"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="identifier"/> is null. </exception>
        public SubjectIdentifierToCompanyType(string identifier)
        {
            if (identifier == null)
            {
                throw new ArgumentNullException(nameof(identifier));
            }

            Identifier = identifier;
            Type = "onip";
        }

        /// <summary> Initializes a new instance of SubjectIdentifierToCompanyType. </summary>
        /// <param name="type"></param>
        /// <param name="identifier"></param>
        internal SubjectIdentifierToCompanyType(string type, string identifier) : base(type)
        {
            Identifier = identifier;
            Type = type ?? "onip";
        }

        /// <summary> Gets or sets the identifier. </summary>
        public string Identifier { get; set; }
    }
}
